language: node_js

sudo: false

branches:
  only:
    - master
    - develop
    - revamp

services:
  - mongodb
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE users;'

os:
  - linux

node_js:
  - "10"
  - "12"

before_script:
  - sleep 15
  - npm prune
  - cp ./.env.example ./.env

script:
  - npm run test:coverage

after_success:
  - npm run codecov
