language: node_js

sudo: false

branches:
  only:
    - master
    - develop
    - "more-datastores"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE users;'

os:
  - linux

node_js:
  - "10"
  - "12"

before_script:
  - npm prune
  - cp ./.env.example ./.env
  - docker run -d -it --rm --name mongodb -p 27017:27017 mongo:4.4.1

script:
  - npm run test:coverage

after_success:
  - npm run codecov
